version: '3'

services:
  backend:
    image: harshiniprojects.azurecr.io/video-app-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  frontend:
    image: harshiniprojects.azurecr.io/video-app-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend